<a href="https://colab.research.google.com/github/rajbaviskar-art/BasicPython/blob/main/9_Libraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Libraries

##Common Third Party Libraries for Data Analytics

- Pandas
- NumPy
- Matplotlib
- Seaborn
- SciPy
- Scikit-learn

Let's try importing a simple csv file within python and run some basic analysis

In [3]:
file = open('/content/sample_data/california_housing_test.csv')

content = file.read()

file.close()

In [6]:
import csv

data_dict = {}
for index, row in enumerate(csv.reader(content.strip().split('\n'))):
  if index == 0:
    # Initialize dictionary with column headers as keys
    for column in row:
      data_dict[column] = []
  else:
    # Append each element in the row to correct the list in dictionary
    for col_index, value in enumerate(row):
      data_dict[list(data_dict.keys())[col_index]].append(value)


data_dict

{'longitude': ['-122.050000',
  '-118.300000',
  '-117.810000',
  '-118.360000',
  '-119.670000',
  '-119.560000',
  '-121.430000',
  '-120.650000',
  '-122.840000',
  '-118.020000',
  '-118.240000',
  '-119.120000',
  '-121.930000',
  '-117.030000',
  '-117.970000',
  '-117.990000',
  '-120.810000',
  '-121.200000',
  '-118.880000',
  '-122.590000',
  '-122.150000',
  '-121.370000',
  '-118.160000',
  '-122.200000',
  '-117.280000',
  '-118.030000',
  '-122.420000',
  '-118.390000',
  '-118.450000',
  '-118.480000',
  '-119.350000',
  '-118.300000',
  '-121.130000',
  '-118.080000',
  '-118.320000',
  '-118.110000',
  '-122.530000',
  '-118.020000',
  '-118.050000',
  '-119.010000',
  '-119.320000',
  '-116.920000',
  '-118.060000',
  '-117.270000',
  '-118.230000',
  '-117.240000',
  '-121.910000',
  '-118.290000',
  '-121.350000',
  '-117.990000',
  '-120.990000',
  '-119.420000',
  '-122.210000',
  '-118.170000',
  '-117.900000',
  '-117.990000',
  '-121.420000',
  '-118.770000',
  '-121.930000',
  '-121.820000',
  '-122.290000',
  '-121.780000',
  '-118.410000',
  '-121.670000',
  '-118.000000',
  '-117.220000',
  '-121.080000',
  '-117.530000',
  '-117.460000',
  '-117.970000',
  '-121.920000',
  '-118.200000',
  '-118.060000',
  '-122.050000',
  '-123.790000',
  '-120.790000',
  '-121.890000',
  '-118.430000',
  '-118.750000',
  '-122.470000',
  '-120.690000',
  '-118.280000',
  '-118.440000',
  '-122.050000',
  '-121.990000',
  '-121.020000',
  '-119.850000',
  '-118.020000',
  '-123.520000',
  '-122.400000',
  '-118.130000',
  '-122.000000',
  '-118.450000',
  '-117.500000',
  '-122.220000',
  '-119.820000',
  '-120.210000',
  '-120.970000',
  '-121.190000',
  '-118.200000',
  '-118.300000',
  '-122.230000',
  '-121.310000',
  '-117.250000',
  '-118.260000',
  '-119.390000',
  '-121.510000',
  '-119.180000',
  '-118.180000',
  '-122.430000',
  '-117.930000',
  '-124.160000',
  '-117.950000',
  '-118.050000',
  '-116.970000',
  '-118.850000',
  '-117.730000',
  '-122.070000',
  '-117.180000',
  '-118.410000',
  '-121.960000',
  '-121.740000',
  '-118.210000',
  '-121.900000',
  '-117.810000',
  '-118.190000',
  '-120.930000',
  '-122.020000',
  '-122.470000',
  '-117.190000',
  '-117.240000',
  '-118.130000',
  '-122.420000',
  '-118.140000',
  '-119.760000',
  '-122.340000',
  '-122.450000',
  '-118.290000',
  '-118.320000',
  '-122.040000',
  '-117.390000',
  '-122.250000',
  '-117.980000',
  '-120.060000',
  '-121.470000',
  '-122.200000',
  '-117.230000',
  '-119.750000',
  '-117.920000',
  '-121.640000',
  '-117.140000',
  '-122.290000',
  '-117.910000',
  '-118.380000',
  '-122.030000',
  '-117.130000',
  '-118.280000',
  '-122.450000',
  '-119.770000',
  '-117.700000',
  '-117.070000',
  '-117.850000',
  '-117.760000',
  '-117.190000',
  '-120.970000',
  '-117.190000',
  '-118.380000',
  '-121.560000',
  '-118.960000',
  '-116.960000',
  '-118.270000',
  '-119.180000',
  '-118.230000',
  '-120.490000',
  '-121.430000',
  '-118.140000',
  '-119.090000',
  '-118.020000',
  '-121.530000',
  '-119.290000',
  '-121.840000',
  '-117.990000',
  '-122.240000',
  '-121.800000',
  '-117.430000',
  '-118.280000',
  '-117.300000',
  '-118.200000',
  '-117.630000',
  '-121.940000',
  '-118.070000',
  '-117.190000',
  '-118.210000',
  '-118.410000',
  '-117.000000',
  '-116.920000',
  '-121.040000',
  '-122.120000',
  '-119.480000',
  '-121.020000',
  '-123.280000',
  '-122.890000',
  '-122.040000',
  '-118.080000',
  '-118.310000',
  '-122.160000',
  '-121.610000',
  '-122.100000',
  '-122.280000',
  '-116.910000',
  '-121.830000',
  '-118.300000',
  '-117.960000',
  '-122.140000',
  '-121.440000',
  '-122.260000',
  '-121.640000',
  '-117.180000',
  '-122.280000',
  '-117.900000',
  '-122.180000',
  '-121.490000',
  '-118.190000',
  '-118.270000',
  '-121.440000',
  '-121.910000',
  '-117.860000',
  '-118.350000',
  '-117.260000',
  '-122.430000',
  '-121.800000',
  '-122.580000',
  '-122.470000',
  '-118.080000',
  '-122.000000',
  '-119.020000',
  '-118.130000',
  '-121.940000',
  '-120.510000',
  '-121.650000',
  '-121.620000',
  '-117.080000',
  '-123.210000',
  '-119.610000',
  '-114.980000',
  '-118.380000',
  '-117.990000',
  '-116.260000',
  '-118.400000',
  '-120.640000',
  '-122.030000',
  '-118.290000',
  '-117.020000',
  '-119.320000',
  '-122.310000',
  '-118.860000',
  '-117.140000',
  '-118.640000',
  '-116.630000',
  '-118.280000',
  '-119.030000',
  '-118.260000',
  '-117.890000',
  '-122.090000',
  '-122.940000',
  '-117.100000',
  '-118.980000',
  '-120.230000',
  '-118.200000',
  '-121.300000',
  '-121.740000',
  '-121.960000',
  '-120.600000',
  '-122.470000',
  '-117.050000',
  '-117.900000',
  '-117.230000',
  '-122.080000',
  '-118.210000',
  '-122.080000',
  '-118.380000',
  '-118.200000',
  '-117.620000',
  '-122.110000',
  '-122.840000',
  '-121.260000',
  '-116.890000',
  '-122.670000',
  '-117.940000',
  '-118.140000',
  '-122.400000',
  '-118.080000',
  '-116.360000',
  '-117.940000',
  '-117.470000',
  '-117.640000',
  '-118.500000',
  '-118.190000',
  '-117.660000',
  '-122.300000',
  '-122.140000',
  '-118.260000',
  '-118.230000',
  '-120.960000',
  '-117.840000',
  '-119.160000',
  '-122.650000',
  '-121.880000',
  '-118.400000',
  '-118.270000',
  '-118.440000',
  '-121.770000',
  '-119.990000',
  '-118.360000',
  '-118.320000',
  '-118.270000',
  '-116.810000',
  '-118.390000',
  '-118.070000',
  '-118.350000',
  '-118.430000',
  '-121.730000',
  '-117.310000',
  '-122.290000',
  '-119.690000',
  '-122.070000',
  '-118.050000',
  '-122.070000',
  '-121.800000',
  '-122.690000',
  '-117.080000',
  '-119.760000',
  '-118.370000',
  '-122.700000',
  '-118.130000',
  '-119.350000',
  '-117.670000',
  '-117.970000',
  '-118.080000',
  '-121.230000',
  '-118.200000',
  '-118.170000',
  '-117.800000',
  '-118.300000',
  '-122.470000',
  '-118.200000',
  '-117.130000',
  '-119.770000',
  '-118.470000',
  '-122.250000',
  '-118.500000',
  '-122.240000',
  '-117.150000',
  '-120.850000',
  '-122.250000',
  '-118.330000',
  '-124.150000',
  '-117.940000',
  '-121.590000',
  '-122.690000',
  '-122.510000',
  '-117.890000',
  '-117.190000',
  '-117.150000',
  '-122.210000',
  '-118.250000',
  '-120.490000',
  '-118.300000',
  '-117.140000',
  '-121.300000',
  '-119.780000',
  '-118.380000',
  '-118.130000',
  '-118.300000',
  '-118.440000',
  '-117.480000',
  '-122.350000',
  '-119.710000',
  '-116.920000',
  '-122.110000',
  '-117.410000',
  '-122.450000',
  '-118.360000',
  '-121.660000',
  '-122.420000',
  '-118.290000',
  '-119.820000',
  '-119.340000',
  '-121.500000',
  '-121.880000',
  '-118.270000',
  '-122.170000',
  '-122.220000',
  '-117.200000',
  '-120.690000',
  '-122.700000',
  '-118.370000',
  '-118.350000',
  '-118.390000',
  '-118.110000',
  '-121.720000',
  '-118.520000',
  '-118.120000',
  '-119.690000',
  '-118.030000',
  '-120.670000',
  '-118.430000',
  '-121.620000',
  '-118.970000',
  '-117.250000',
  '-122.280000',
  '-118.190000',
  '-117.900000',
  '-119.020000',
  '-118.370000',
  '-122.410000',
  '-117.940000',
  '-118.220000',
  '-117.240000',
  '-122.080000',
  '-122.280000',
  '-118.210000',
  '-118.010000',
  '-118.290000',
  '-118.210000',
  '-117.230000',
  '-117.030000',
  '-121.850000',
  '-122.400000',
  '-120.470000',
  '-121.140000',
  '-119.340000',
  '-117.660000',
  '-116.840000',
  '-118.290000',
  '-119.980000',
  '-118.100000',
  '-120.070000',
  '-119.110000',
  '-117.720000',
  '-117.900000',
  '-121.980000',
  '-122.030000',
  '-117.420000',
  '-117.660000',
  '-119.290000',
  '-117.020000',
  '-122.850000',
  '-118.330000',
  '-118.400000',
  '-118.380000',
  '-118.050000',
  '-117.430000',
  '-118.100000',
  '-122.530000',
  '-118.300000',
  '-118.200000',
  '-118.020000',
  '-121.530000',
  '-117.920000',
  '-118.370000',
  '-118.040000',
  '-118.460000',
  '-118.050000',
  '-122.950000',
  '-122.000000',
  '-121.860000',
  '-119.250000',
  '-118.210000',
  '-118.260000',
  '-117.280000',
  '-122.440000',
  '-118.990000',
  '-117.140000',
  '-122.150000',
  '-121.200000',
  '-122.150000',
  '-118.340000',
  '-118.250000',
  '-119.580000',
  '-121.310000',
  '-118.420000',
  '-117.180000',
  '-115.900000',
  '-118.360000',
  '-122.500000',
  '-121.500000',
  '-118.190000',
  '-117.300000',
  '-118.420000',
  '-118.120000',
  '-119.800000',
  '-119.740000',
  '-121.970000',
  '-117.070000',
  '-122.290000',
  '-116.310000',
  '-118.270000',
  '-122.440000',
  '-118.270000',
  '-118.410000',
  '-121.450000',
  '-117.250000',
  '-119.800000',
  '-121.310000',
  '-118.180000',
  '-122.130000',
  '-119.750000',
  '-117.090000',
  '-122.020000',
  '-117.200000',
  '-118.140000',
  '-122.430000',
  '-118.100000',
  '-118.350000',
  '-118.000000',
  '-121.460000',
  '-118.270000',
  '-118.260000',
  '-119.010000',
  '-117.080000',
  '-122.200000',
  '-119.980000',
  '-122.530000',
  '-118.300000',
  '-121.860000',
  '-122.060000',
  '-122.450000',
  '-117.010000',
  '-120.870000',
  '-121.790000',
  '-117.810000',
  '-117.590000',
  '-117.360000',
  '-121.520000',
  '-122.270000',
  '-122.210000',
  '-117.240000',
  '-122.550000',
  '-118.450000',
  '-117.880000',
  '-117.180000',
  '-118.300000',
  '-122.040000',
  '-122.430000',
  '-118.380000',
  '-119.570000',
  '-117.870000',
  '-116.880000',
  '-118.580000',
  '-122.040000',
  '-122.440000',
  '-121.810000',
  '-122.500000',
  '-121.940000',
  '-118.450000',
  '-121.700000',
  '-118.100000',
  '-119.020000',
  '-118.060000',
  '-117.660000',
  '-117.400000',
  '-118.190000',
  '-121.550000',
  '-121.980000',
  '-117.060000',
  '-118.320000',
  '-117.130000',
  '-122.500000',
  '-120.870000',
  '-118.240000',
  '-117.690000',
  '-122.200000',
  '-117.080000',
  '-117.910000',
  '-122.000000',
  '-118.290000',
  '-118.130000',
  '-118.350000',
  '-122.130000',
  '-122.070000',
  '-117.260000',
  '-117.870000',
  '-121.880000',
  '-121.670000',
  '-116.890000',
  '-122.660000',
  '-121.450000',
  '-121.000000',
  '-117.270000',
  '-117.870000',
  '-121.440000',
  '-118.130000',
  '-118.310000',
  '-122.000000',
  '-122.270000',
  '-120.890000',
  '-118.750000',
  '-118.180000',
  '-121.370000',
  '-120.310000',
  '-117.880000',
  '-117.330000',
  '-118.490000',
  '-121.930000',
  '-122.450000',
  '-117.080000',
  '-116.190000',
  '-119.730000',
  '-117.120000',
  '-117.630000',
  '-118.260000',
  '-118.260000',
  '-119.840000',
  '-121.280000',
  '-117.350000',
  '-121.320000',
  '-118.350000',
  '-119.810000',
  '-118.150000',
  '-121.220000',
  '-119.720000',
  '-117.850000',
  '-117.200000',
  '-118.630000',
  '-117.490000',
  '-118.370000',
  '-122.020000',
  '-121.330000',
  '-118.740000',
  '-117.890000',
  '-117.410000',
  '-118.750000',
  '-122.480000',
  '-118.140000',
  '-122.560000',
  '-122.090000',
  '-121.800000',
  '-117.830000',
  '-121.680000',
  '-122.300000',
  '-121.040000',
  '-118.320000',
  '-118.120000',
  '-121.810000',
  '-121.840000',
  '-121.790000',
  '-118.160000',
  '-119.400000',
  '-122.270000',
  '-117.730000',
  '-121.280000',
  '-119.810000',
  '-122.260000',
  '-117.950000',
  '-120.120000',
  '-121.880000',
  '-118.110000',
  '-122.080000',
  '-121.680000',
  '-122.160000',
  '-118.070000',
  '-117.690000',
  '-118.350000',
  '-122.790000',
  '-118.140000',
  '-121.890000',
  '-122.410000',
  '-118.600000',
  '-118.410000',
  '-117.530000',
  '-117.130000',
  '-117.140000',
  '-118.160000',
  '-117.180000',
  '-117.970000',
  '-118.250000',
  '-118.140000',
  '-120.010000',
  '-117.410000',
  '-118.220000',
  '-117.910000',
  '-117.090000',
  '-122.270000',
  '-118.200000',
  '-118.360000',
  '-122.000000',
  '-121.360000',
  '-122.000000',
  '-117.700000',
  '-118.280000',
  '-118.250000',
  '-122.540000',
  '-118.250000',
  '-122.060000',
  '-122.450000',
  '-118.040000',
  '-118.120000',
  '-118.310000',
  '-118.440000',
  '-118.460000',
  '-117.930000',
  '-121.810000',
  '-118.420000',
  '-118.330000',
  '-118.240000',
  '-116.940000',
  '-122.600000',
  '-118.210000',
  '-118.730000',
  '-122.120000',
  '-122.420000',
  '-122.130000',
  '-121.170000',
  '-122.430000',
  '-118.220000',
  '-121.170000',
  '-122.270000',
  '-119.190000',
  '-122.410000',
  '-116.830000',
  '-119.340000',
  '-123.220000',
  '-121.920000',
  '-116.570000',
  '-118.170000',
  '-117.200000',
  '-117.580000',
  '-118.240000',
  '-122.240000',
  '-119.690000',
  '-121.690000',
  '-119.280000',
  '-117.990000',
  '-117.650000',
  '-118.150000',
  '-122.430000',
  '-117.040000',
  '-118.080000',
  '-121.070000',
  '-117.120000',
  '-118.130000',
  '-122.220000',
  '-122.520000',
  '-122.090000',
  '-117.970000',
  '-118.280000',
  '-118.390000',
  '-122.400000',
  '-118.260000',
  '-122.160000',
  '-117.430000',
  '-118.280000',
  '-118.370000',
  '-121.490000',
  '-121.800000',
  '-122.190000',
  '-118.010000',
  '-118.310000',
  '-121.060000',
  '-121.350000',
  '-118.310000',
  '-121.930000',
  '-117.310000',
  '-120.890000',
  '-119.470000',
  '-118.410000',
  '-119.810000',
  '-117.080000',
  '-119.270000',
  '-122.310000',
  '-117.200000',
  '-118.430000',
  '-121.520000',
  '-118.770000',
  '-124.100000',
  '-117.150000',
  '-118.370000',
  '-122.500000',
  '-120.920000',
  '-122.470000',
  '-117.890000',
  '-121.350000',
  '-117.920000',
  '-118.310000',
  '-120.350000',
  '-122.000000',
  '-118.010000',
  '-118.070000',
  '-117.500000',
  '-123.740000',
  '-122.030000',
  '-118.910000',
  '-117.960000',
  '-121.800000',
  '-122.290000',
  '-122.140000',
  '-117.850000',
  '-122.100000',
  '-122.120000',
  '-119.290000',
  '-117.400000',
  '-117.060000',
  '-118.300000',
  '-122.230000',
  '-117.910000',
  '-122.530000',
  '-121.790000',
  '-118.460000',
  '-118.030000',
  '-122.320000',
  '-118.280000',
  '-119.140000',
  '-117.130000',
  '-120.670000',
  '-118.060000',
  '-122.390000',
  '-118.390000',
  '-118.160000',
  '-122.580000',
  '-118.020000',
  '-119.700000',
  '-122.680000',
  '-121.350000',
  '-121.980000',
  '-118.080000',
  '-118.250000',
  '-122.250000',
  '-119.050000',
  '-117.540000',
  '-118.210000',
  '-117.200000',
  '-120.960000',
  '-118.240000',
  '-118.270000',
  '-122.250000',
  '-117.300000',
  '-120.910000',
  '-122.160000',
  '-118.310000',
  '-118.180000',
  '-117.970000',
  '-117.950000',
  '-118.030000',
  '-118.380000',
  '-119.820000',
  '-122.060000',
  '-122.410000',
  '-117.880000',
  '-120.800000',
  '-118.100000',
  '-118.090000',
  '-118.310000',
  '-118.020000',
  '-121.940000',
  '-117.950000',
  '-118.150000',
  '-121.810000',
  '-121.810000',
  '-121.280000',
  '-118.430000',
  '-121.380000',
  '-117.680000',
  '-117.690000',
  '-118.240000',
  '-117.700000',
  '-118.380000',
  '-117.050000',
  '-121.380000',
  '-117.100000',
  '-122.470000',
  '-117.840000',
  '-122.260000',
  '-118.400000',
  '-122.370000',
  '-117.980000',
  '-122.700000',
  '-118.410000',
  '-121.920000',
  '-122.110000',
  '-121.870000',
  '-120.180000',
  '-117.060000',
  '-117.240000',
  '-118.250000',
  '-117.800000',
  '-119.780000',
  '-117.040000',
  '-118.290000',
  '-118.360000',
  '-122.420000',
  '-118.420000',
  '-121.100000',
  '-117.740000',
  '-122.390000',
  '-118.370000',
  '-122.080000',
  '-118.440000',
  '-121.370000',
  '-122.100000',
  '-117.220000',
  '-122.130000',
  '-122.300000',
  '-123.410000',
  '-120.770000',
  '-118.800000',
  '-119.270000',
  '-122.470000',
  '-118.260000',
  '-119.770000',
  '-124.160000',
  '-119.030000',
  '-122.180000',
  '-123.850000',
  '-122.700000',
  '-118.100000',
  '-117.990000',
  '-121.930000',
  '-118.440000',
  '-118.320000',
  '-118.150000',
  '-117.740000',
  '-121.350000',
  '-122.750000',
  '-120.660000',
  '-122.620000',
  '-117.220000',
  '-117.920000',
  '-122.280000',
  '-118.120000',
  '-119.190000',
  '-117.970000',
  '-118.090000',
  '-121.930000',
  '-122.650000',
  '-122.490000',
  '-122.310000',
  '-121.270000',
  '-118.390000',
  '-118.390000',
  '-117.150000',
  '-122.090000',
  '-117.060000',
  '-122.330000',
  '-116.920000',
  '-116.000000',
  '-117.690000',
  '-117.230000',
  '-117.180000',
  '-121.330000',
  '-121.880000',
  '-122.520000',
  '-117.770000',
  '-121.010000',
  '-117.330000',
  '-118.240000',
  '-117.800000',
  '-119.620000',
  '-122.160000',
  '-117.970000',
  '-120.870000',
  '-120.460000',
  '-118.230000',
  '-121.070000',
  '-120.090000',
  '-118.210000',
  '-122.630000',
  '-119.400000',
  '-117.380000',
  '-117.250000',
  '-122.230000',
  '-121.230000',
  '-121.550000',
  '-117.890000',
  '-117.230000',
  '-117.920000',
  '-117.580000',
  '-120.850000',
  '-121.530000',
  '-117.210000',
  '-117.350000',
  '-118.170000',
  '-118.300000',
  '-118.020000',
  '-116.990000',
  '-122.560000',
  '-118.150000',
  '-117.930000',
  '-121.090000',
  '-116.660000',
  '-118.260000',
  '-117.940000',
  '-116.930000',
  '-122.290000',
  '-122.480000',
  '-119.330000',
  '-118.410000',
  '-119.500000',
  '-118.330000',
  '-118.300000',
  ...],
 'latitude': ['37.370000',
  '34.260000',
  '33.780000',
  '33.820000',
  '36.330000',
  '36.510000',
  '38.630000',
  '35.480000',
  '38.400000',
  '34.080000',
  '33.980000',
  '35.850000',
  '37.250000',
  '32.970000',
  '33.730000',
  '33.810000',
  '37.530000',
  '38.690000',
  '34.210000',
  '38.010000',
  '37.750000',
  '38.680000',
  '34.070000',
  '37.790000',
  '33.280000',
  '34.160000',
  '37.760000',
  '33.990000',
  '34.070000',
  '34.010000',
  '36.330000',
  '33.910000',
  '39.310000',
  '34.550000',
  '33.940000',
  '34.000000',
  '37.970000',
  '33.920000',
  '33.930000',
  '34.230000',
  '36.200000',
  '32.770000',
  '34.150000',
  '34.090000',
  '34.130000',
  '33.170000',
  '37.440000',
  '33.940000',
  '38.000000',
  '33.780000',
  '37.700000',
  '35.970000',
  '37.800000',
  '33.800000',
  '34.090000',
  '33.930000',
  '38.720000',
  '34.260000',
  '37.330000',
  '37.250000',
  '37.560000',
  '37.230000',
  '34.000000',
  '40.870000',
  '33.920000',
  '32.730000',
  '37.690000',
  '33.920000',
  '34.080000',
  '33.860000',
  '37.330000',
  '34.040000',
  '33.800000',
  '37.360000',
  '39.500000',
  '37.490000',
  '37.350000',
  '34.200000',
  '34.170000',
  '37.990000',
  '37.400000',
  '34.050000',
  '34.250000',
  '38.260000',
  '37.350000',
  '37.680000',
  '36.740000',
  '34.080000',
  '41.010000',
  '37.620000',
  '34.150000',
  '37.980000',
  '34.250000',
  '33.870000',
  '37.840000',
  '36.640000',
  '36.770000',
  '38.420000',
  '38.870000',
  '33.770000',
  '34.020000',
  '37.790000',
  '38.620000',
  '32.800000',
  '33.990000',
  '36.540000',
  '38.520000',
  '34.270000',
  '33.770000',
  '37.740000',
  '33.910000',
  '40.770000',
  '33.630000',
  '34.100000',
  '32.810000',
  '34.170000',
  '33.630000',
  '37.340000',
  '33.020000',
  '34.000000',
  '37.300000',
  '38.550000',
  '33.920000',
  '36.610000',
  '33.840000',
  '33.930000',
  '37.730000',
  '37.960000',
  '37.790000',
  '34.030000',
  '32.800000',
  '34.100000',
  '37.730000',
  '34.710000',
  '36.750000',
  '37.560000',
  '40.460000',
  '33.910000',
  '33.910000',
  '37.360000',
  '34.100000',
  '37.800000',
  '34.100000',
  '36.950000',
  '39.490000',
  '37.790000',
  '32.750000',
  '36.740000',
  '34.030000',
  '39.280000',
  '32.720000',
  '37.540000',
  '33.940000',
  '34.270000',
  '37.600000',
  '33.150000',
  '34.000000',
  '37.720000',
  '36.770000',
  '33.640000',
  '32.790000',
  '33.620000',
  '33.710000',
  '34.940000',
  '37.690000',
  '33.640000',
  '33.910000',
  '38.260000',
  '35.870000',
  '32.800000',
  '33.940000',
  '34.190000',
  '33.900000',
  '37.260000',
  '38.640000',
  '34.170000',
  '35.410000',
  '33.710000',
  '39.060000',
  '34.280000',
  '37.340000',
  '33.880000',
  '37.550000',
  '37.310000',
  '34.080000',
  '34.020000',
  '33.060000',
  '34.040000',
  '34.110000',
  '37.330000',
  '33.930000',
  '32.830000',
  '33.890000',
  '34.190000',
  '32.800000',
  '32.860000',
  '38.950000',

In [7]:
sum(data_dict['total_rooms'])

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [10]:
sum(float(room.replace(' ','')) for room in data_dict['total_rooms'] if room.replace(' ', '').replace('.',''). isdigit())

7798736.0

The above method of importing data and processing it using basic python code and functions is cumbersome and can be done easily using libraries. Below we will be using pandas library to bring in data and process the same file

In [13]:
import pandas as pd

contents = pd.read_csv('/content/sample_data/california_housing_test.csv')

contents

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [14]:
contents['total_bedrooms']

0        661.0
1        310.0
2        507.0
3         15.0
4        244.0
         ...
2995     642.0
2996    1082.0
2997     201.0
2998      14.0
2999     263.0
Name: total_bedrooms, Length: 3000, dtype: float64

In [16]:
print(contents['total_bedrooms'].sum())

1589852.0

How to install and check what packages are available in google colab

In [17]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [18]:
!pip list

Package                                  Version
---------------------------------------- -------------------
absl-py                                  1.4.0
accelerate                               1.13.0
access                                   1.1.10.post3
affine                                   2.4.0
aiofiles                                 24.1.0
aiohappyeyeballs                         2.6.1
aiohttp                                  3.13.5
aiosignal                                1.4.0
aiosqlite                                0.22.1
alabaster                                1.0.0
albucore                                 0.0.24
albumentations                           2.0.8
ale-py                                   0.11.2
alembic                                  1.18.4
altair                                   5.5.0
annotated-doc                            0.0.4
annotated-types                          0.7.0
antlr4-python3-runtime                   4.9.3
anyio                                    4.13.0
anywidget                                0.9.21
apsw                                     3.53.0.0
apswutils                                0.1.2
argon2-cffi                              25.1.0
argon2-cffi-bindings                     25.1.0
array_record                             0.8.3
arrow                                    1.4.0
arviz                                    0.22.0
astropy                                  7.2.0
astropy-iers-data                        0.2026.4.20.0.58.15
astunparse                               1.6.3
atpublic                                 5.1
attrs                                    26.1.0
audioread                                3.1.0
Authlib                                  1.6.11
autograd                                 1.8.0
babel                                    2.18.0
backcall                                 0.2.0
beartype                                 0.22.9
beautifulsoup4                           4.13.5
betterproto                              2.0.0b6
bigframes                                2.39.0
bigquery-magics                          0.14.0
bleach                                   6.3.0
blinker                                  1.9.0
blis                                     1.3.3
blobfile                                 3.2.0
blosc2                                   4.1.2
bokeh                                    3.8.2
Bottleneck                               1.4.2
bqplot                                   0.12.45
branca                                   0.8.2
brotli                                   1.2.0
CacheControl                             0.14.4
cachetools                               6.2.6
catalogue                                2.0.10
certifi                                  2026.4.22
cffi                                     2.0.0
chardet                                  5.2.0
charset-normalizer                       3.4.7
clarabel                                 0.11.1
click                                    8.3.3
click-plugins                            1.1.1.2
cligj                                    0.7.2
cloudpathlib                             0.23.0
cloudpickle                              3.1.2
cmake                                    3.31.10
cmdstanpy                                1.3.0
colorcet                                 3.1.0
colorlover                               0.3.0
community                                1.0.0b1
confection                               1.3.3
cons                                     0.4.7
contourpy                                1.3.3
cramjam                                  2.11.0
cryptography                             43.0.3
cufflinks                                0.17.3
curl_cffi                                0.15.0
cvxopt                                   1.3.2
cvxpy                                    1.6.7
cycler                                   0.12.1
cyipopt                                  1.5.0
cymem                                    2.0.13
Cython                                   3.0.12
dask                                     2026.3.0
dataproc-spark-connect                   1.1.0
datasets                                 4.0.0
db-dtypes                                1.5.1
dbus-python                              1.2.18
debugpy                                  1.8.15
decorator                                4.4.2
defusedxml                               0.7.1
deprecation                              2.1.0
diffusers                                0.37.1
dill                                     0.3.8
distro                                   1.9.0
dlib                                     19.24.6
dm-tree                                  0.1.10
docstring_parser                         0.18.0
docutils                                 0.21.2
dopamine_rl                              4.1.2
duckdb                                   1.3.2
earthengine-api                          1.7.22
easydict                                 1.13
editdistance                             0.8.1
eerepr                                   0.1.2
einops                                   0.8.2
en_core_web_sm                           3.8.0
entrypoints                              0.4
esda                                     2.9.0
et_xmlfile                               2.0.0
etils                                    1.14.0
etuples                                  0.3.10
Farama-Notifications                     0.0.4
fastai                                   2.8.7
fastapi                                  0.136.1
fastcore                                 1.12.42
fastdownload                             0.0.7
fastjsonschema                           2.21.2
fastlite                                 0.2.4
fastprogress                             1.1.5
fasttransform                            0.0.2
ffmpy                                    1.0.0
filelock                                 3.29.0
fiona                                    1.10.1
firebase-admin                           6.9.0
Flask                                    3.1.3
flatbuffers                              25.12.19
flax                                     0.11.2
folium                                   0.20.0
fonttools                                4.62.1
fqdn                                     1.5.1
frozendict                               2.4.7
frozenlist                               1.8.0
fsspec                                   2025.3.0
future                                   1.0.0
gast                                     0.7.0
gcsfs                                    2025.3.0
GDAL                                     3.8.4
gdown                                    5.2.2
geemap                                   0.37.2
geocoder                                 1.38.1
geographiclib                            2.1
geopandas                                1.1.3
geopy                                    2.4.1
giddy                                    2.3.6
gin-config                               0.5.0
gitdb                                    4.0.12
GitPython                                3.1.47
glob2                                    0.7
google                                   3.0.0
google-adk                               1.29.0
google-ai-generativelanguage             0.6.15
google-api-core                          2.30.3
google-api-python-client                 2.194.0
google-auth                              2.47.0
google-auth-httplib2                     0.3.1
google-auth-oauthlib                     1.3.1
google-cloud-aiplatform                  1.148.1
google-cloud-appengine-logging           1.9.0
google-cloud-audit-log                   0.5.0
google-cloud-bigquery                    3.41.0
google-cloud-bigquery-connection         1.21.0
google-cloud-bigquery-storage            2.37.0
google-cloud-bigtable                    2.36.0
google-cloud-core                        2.5.1
google-cloud-dataplex                    2.18.0
google-cloud-dataproc                    5.27.0
google-cloud-datastore                   2.24.0
google-cloud-discoveryengine             0.13.12
google-cloud-firestore                   2.27.0
google-cloud-functions                   1.23.0
google-cloud-iam                         2.22.0
google-cloud-language                    2.20.0
google-cloud-logging                     3.15.0
google-cloud-monitoring                  2.30.0
google-cloud-pubsub                      2.37.0
google-cloud-resource-manager            1.17.0
google-cloud-secret-manager              2.27.0
google-cloud-spanner                     3.65.0
google-cloud-speech                      2.38.0
google-cloud-storage                     3.10.1
google-cloud-trace                       1.19.0
google-cloud-translate                   3.26.0
google-colab                             1.0.0
google-crc32c                            1.8.0
google-genai                             1.68.0
google-generativeai                      0.8.6
google-pasta                             0.2.0
google-resumable-media                   2.8.2
googleapis-common-protos                 1.74.0
googledrivedownloader                    1.1.0
gradio                                   5.50.0
gradio_client                            1.14.0
grain                                    0.2.16
graphviz                                 0.21
greenlet                                 3.4.0
groovy                                   0.1.2
grpc-google-iam-v1                       0.14.4
grpc-interceptor                         0.15.4
grpcio                                   1.80.0
grpcio-status                            1.71.2
grpclib                                  0.4.9
gspread                                  6.2.1
gspread-dataframe                        4.0.0
gym                                      0.25.2
gym-notices                              0.1.0
gymnasium                                1.3.0
h11                                      0.16.0
h2                                       4.3.0
h5netcdf                                 1.8.1
h5py                                     3.16.0
hdbscan                                  0.8.42
hf-xet                                   1.4.3
highspy                                  1.14.0
holidays                                 0.95
holoviews                                1.22.1
hpack                                    4.1.0
html5lib                                 1.1
httpcore                                 1.0.9
httpimport                               1.4.1
httplib2                                 0.31.2
httptools                                0.7.1
httpx                                    0.28.1
httpx-sse                                0.4.3
huggingface_hub                          1.11.0
humanize                                 4.15.0
hyperframe                               6.1.0
hyperopt                                 0.2.7
ibis-framework                           9.5.0
idna                                     3.13
ImageIO                                  2.37.3
imageio-ffmpeg                           0.6.0
imagesize                                2.0.0
imbalanced-learn                         0.14.1
immutabledict                            4.3.1
importlib_metadata                       8.7.1
importlib_resources                      7.1.0
imutils                                  0.5.4
inequality                               1.1.2
inflect                                  7.5.0
iniconfig                                2.3.0
intel-cmplr-lib-ur                       2025.3.3
intel-openmp                             2025.3.3
ipyevents                                2.0.4
ipyfilechooser                           0.6.0
ipykernel                                6.17.1
ipyleaflet                               0.20.0
ipyparallel                              8.8.0
ipython                                  7.34.0
ipython-genutils                         0.2.0
ipython-sql                              0.5.0
ipywidgets                               7.7.1
isoduration                              20.11.0
itsdangerous                             2.2.0
jaraco.classes                           3.4.0
jaraco.context                           6.1.2
jaraco.functools                         4.4.0
jax                                      0.7.2
jaxlib                                   0.7.2
jeepney                                  0.9.0
jieba                                    0.42.1
Jinja2                                   3.1.6
jiter                                    0.14.0
joblib                                   1.5.3
jsonpatch                                1.33
jsonpickle                               4.1.1
jsonpointer                              3.1.1
jsonschema                               4.26.0
jsonschema-specifications                2025.9.1
jupyter_client                           7.4.9
jupyter-console                          6.6.3
jupyter_core                             5.9.1
jupyter-events                           0.12.1
jupyter_kernel_gateway                   2.5.2
jupyter-leaflet                          0.20.0
jupyter_server                           2.14.0
jupyter_server_terminals                 0.5.4
jupyterlab_pygments                      0.3.0
jupyterlab_widgets                       3.0.16
jupytext                                 1.19.1
kaggle                                   2.0.2
kagglehub                                1.0.0
kagglesdk                                0.1.20
keras                                    3.13.2
keras-hub                                0.26.0
keras-nlp                                0.26.0
keyring                                  25.7.0
keyrings.google-artifactregistry-auth    1.1.2
kiwisolver                               1.5.0
langchain                                1.2.15
langchain-core                           1.3.1
langgraph                                1.1.9
langgraph-checkpoint                     4.0.2
langgraph-prebuilt                       1.0.10
langgraph-sdk                            0.3.13
langsmith                                0.7.34
lark                                     1.3.1
launchpadlib                             1.10.16
lazr.restfulclient                       0.14.4
lazr.uri                                 1.0.6
lazy-loader                              0.5
libclang                                 18.1.1
libpysal                                 4.14.1
librosa                                  0.11.0
lightgbm                                 4.6.0
linkify-it-py                            2.1.0
llvmlite                                 0.43.0
locket                                   1.0.0
logical-unification                      0.4.7
lxml                                     6.1.0
Mako                                     1.3.11
mapclassify                              2.10.0
Markdown                                 3.10.2
markdown-it-py                           4.0.0
MarkupSafe                               3.0.3
matplotlib                               3.10.0
matplotlib-inline                        0.2.1
matplotlib-venn                          1.1.2
mcp                                      1.27.0
mdit-py-plugins                          0.5.0
mdurl                                    0.1.2
mgwr                                     2.2.1
miniKanren                               1.0.5
missingno                                0.5.2
mistune                                  3.2.0
mizani                                   0.13.5
mkl                                      2025.3.1
ml_dtypes                                0.5.4
mlxtend                                  0.23.4
mmh3                                     5.2.1
momepy                                   0.11.0
more-itertools                           10.8.0
moviepy                                  1.0.3
mpmath                                   1.3.0
msgpack                                  1.1.2
multidict                                6.7.1
multipledispatch                         1.0.0
multiprocess                             0.70.16
multitasking                             0.0.13
murmurhash                               1.0.15
music21                                  9.9.1
namex                                    0.1.0
narwhals                                 2.20.0
natsort                                  8.4.0
nbclassic                                1.3.3
nbclient                                 0.10.4
nbconvert                                7.17.1
nbformat                                 5.10.4
ndindex                                  1.10.1
nest-asyncio                             1.6.0
networkx                                 3.6.1
nibabel                                  5.4.2
nltk                                     3.9.1
notebook                                 6.5.7
notebook_shim                            0.2.4
numba                                    0.60.0
numexpr                                  2.14.1
numpy                                    2.0.2
nvidia-nccl-cu12                         2.30.4
oauth2client                             4.1.3
oauthlib                                 3.3.1
omegaconf                                2.3.0
onemkl-license                           2025.3.1
openai                                   2.32.0
opencv-contrib-python                    4.13.0.92
opencv-python                            4.13.0.92
opencv-python-headless                   4.13.0.92
openpyxl                                 3.1.5
opentelemetry-api                        1.38.0
opentelemetry-exporter-gcp-logging       1.11.0a0
opentelemetry-exporter-gcp-monitoring    1.11.0a0
opentelemetry-exporter-gcp-trace         1.11.0
opentelemetry-exporter-otlp-proto-common 1.38.0
opentelemetry-exporter-otlp-proto-http   1.38.0
opentelemetry-proto                      1.38.0
opentelemetry-resourcedetector-gcp       1.11.0a0
opentelemetry-sdk                        1.38.0
opentelemetry-semantic-conventions       0.59b0
opt_einsum                               3.4.0
optax                                    0.2.8
optree                                   0.19.0
orbax-checkpoint                         0.11.36
orjson                                   3.11.8
ormsgpack                                1.12.2
osqp                                     1.1.1
overrides                                7.7.0
packaging                                26.1
pandas                                   2.2.2
pandas-datareader                        0.10.0
pandas-gbq                               0.30.0
pandas-stubs                             2.2.2.240909
pandocfilters                            1.5.1
panel                                    1.8.10
param                                    2.3.3
parso                                    0.8.6
parsy                                    2.2
partd                                    1.4.2
patsy                                    1.0.2
peewee                                   4.0.5
peft                                     0.19.1
pexpect                                  4.9.0
pickleshare                              0.7.5
pillow                                   11.3.0
pip                                      24.1.2
platformdirs                             4.9.6
plotly                                   5.24.1
plotnine                                 0.14.5
pluggy                                   1.6.0
plum-dispatch                            2.8.0
pointpats                                2.5.5
polars                                   1.35.2
polars-runtime-32                        1.35.2
pooch                                    1.9.0
portpicker                               1.5.2
preshed                                  3.0.13
prettytable                              3.17.0
proglog                                  0.1.12

In [19]:
!pip install pyjokes

Collecting pyjokes
  Downloading pyjokes-0.8.3-py3-none-any.whl.metadata (3.4 kB)
Downloading pyjokes-0.8.3-py3-none-any.whl (47 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 kB 2.2 MB/s eta 0:00:00
Installing collected packages: pyjokes
Successfully installed pyjokes-0.8.3

In [20]:
import pyjokes

In [21]:
pyjokes.get_joke()

"What's the object-oriented way to become wealthy? Inheritance."

**Module:** A module is a single python file containing definitions and statements



**Package:** A collection of python modules under a common namespace. This is achieved by having a directory with a special `__init__.py` file.

**Library:** A collection of packages or modules that are grouped together to provide functionality that can be utilized by other programs.